---
broadcast-tag: [BROADCAST]
broadcast-color: 

bgod-tag: [GOD]
bgod-color:

bhero-tag: [HEROBRINE]
bhero-color:

announce-tag: [ANNOUNCE]
announce-color:

server-tag: [SERVER]
server-color:

console-tag: [CONSOLE]
console-color:

bcia-tag: [CIA]
bcia-color:
...